server.port=8080
spring.application.name=SpringCloudGateway

# JWT Secret — same value must be in UserManagementMS
jwt.secret=MySuperSecretKey12345MySuperSecretKey12345MySuperSecretKey12345
#
## CORS — allow Angular frontend
##spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:4200
##spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
##spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
##spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

logging.level.org.springframework.cloud.gateway=INFO
logging.level.com.spring.cloudgateway=DEBUG



